---
title: FAKIN auf FDM Netzwerkveranstaltung des BMBF
author: Michael Rustler
date: '2017-06-01'
slug: fakin-fdm-netzwerk
categories: ["data management"]
tags: ["data management", "network"]
---

Am 1.6.2017 fand die Auftaktveranstaltung des BMBF zur Vernetzung und 
Identifikation von Synergiepotenzialen im Harnack Haus der Max Planck 
Gesellschaft in Berlin statt auf der wir (Hauke Sonnenberg & Michael Rustler) das 
Projekt FAKIN in zwei verschiedenen Sessions (Kompetenzen & Disziplin-spezifische 
Besonderheiten im FDM) mit Redebeitragen vorgestellt haben. 

#### Begrüßung durch Vertreter des BMBF

- Die "Digitale Agenda" steht im Koalitionsvertrag der Bundes
- Deutsches Internet-Institut
- Digitaler Wandel in der Wissenschaft
- Rat für Informationsinfrastrukturen gibt Handlungsempfehlungen
- Nationale Forschungsdateninfrastruktur (NFDI) ist ein System (Vernetzung) und
  ein Prozess (sie entwickelt sich)
- Von 73 Anträgen wurden 34 angenommen (`r paste(round(34/73*100, 1), "%")`),
  in nur acht davon werden außeruniversitäre Einrichtungen gefördert.

#### Hinweise an das KWB in persönlichen Gesprächen

- Wir sollten Datenzentren (= Repositorien) nutzen. Ausgangspunkt dafür kann
  [re3data](http://www.re3data.org) sein, eine Art Suchmaschine für solche 
  Datenzentren.
  
- Wir sollten uns Kooperationspartner (z.B. Uni mit Rechenzentrum?) suchen

### Session 1: Kompetenzen

### Session 2: Kooperationen

#### Projekt UNEKE, [Ania Lopez](https://www.uni-due.de/zim/services/suchdienste/mitarbeiter.php?id=50724), Uni Duisburg

- Partner: Uni Essen, RWTH Aachen
- Ziel: Kriterienkatalog: Nach welchen Kriterien wird entschieden, welche 
  Systeme genutzt werden?
- **Statement** Bela Brenger (RWTH Aachen): praxisnahe Handlungsanweisungen

#### Projekt FoDaKo, [Hans-Dieter Weckmann](https://www.zim.hhu.de/nc/das-zim/mitarbeiterinnen-und-mitarbeiter/detailansicht.html?tt_address%5Bperson%5D=2623&tt_address%5Bfunktion%5D=3011), Uni Düsseldorf

- Partner: drei Universitäten: Düsseldorf, Siegen, Wuppertal
- Digitale Langzeitarchivierung und FDM
- Rechenzentren und Bibliotheken
- bereits geschehen: Evaluation von Software, Anforderungskatalog
- bereits vorhanden: 
    + dreistufige IT-Infrastruktur, u.a. Sharepoint, Open Source,
      insgesamt 2 PByte (1 PByte = 1000 GByte) Speicher, verteilt auf drei 
      Zentren
    + Richtlinien
- wichtig: verbindliches commitment
- Projektziel: 
    + Aufbau von *Kompetenzzentren*, die die vorhandenen Strukturen 
      den Wissenschaftlern "andienen"
    + Schulungen
- **Statement** Sabine Roller (Uni Siegen): Schulungsunterlagen

#### Projekt SynFo, [Thilo Paul-Stüve](https://www.rz.uni-kiel.de/de/ueber-uns/a-z/tpaul-stueve), Uni Kiel

- Uni Kiel: datengetriebene Forschung, u.a. Sonderforschungsbereiche SFB 1182
  (Entstehen und Funktionieren von Metaorganismen), SFB 754 (Klima - 
  Biogeochemische Wechselwirkungen im Tropischen Ozean)
- Exzellenzcluster
- Datenflüsse schwierig
- Ziel: Workflows beleuchten
    + organisatorisch
    + technisch, z.B. Metadatenformate
    + rechtlich, z.B. Urheberschaft, Lizenzen
- Produkte
    + Vorgehensweisen, workflows (generisch)
    + Data Policy Kit (Baukastensystem)
    + Musterverträge, Richtlinienblaupausen

#### Projekt FDMentor, [Malte Dreyer](https://www.cms.hu-berlin.de/de/ueberblick/personal/1686433), HU Berlin

- Partner: HUB, FUB, TUB, Uni Potsdam (UP)
- Good Practice im FDM
- Idee Mentor: es sind unterschiedliche Niveaus vorhanden
- Elemente
    + Strategieentwicklung (UP)
    + FD Policies (TUB)
    + Schulungen, Trainings (FUB, HUB): schlechte Skalierung wegen Fluktuationen
    + Verbund (HUB): Vernetzung, Koordination
- Ziel: Handlungsempfehlungen, Policies
- Austausch mit Repositories
- re3data: Wie finde ich das passende Repository?
- Herausforderung: Adressierung und Ansprache von Wissenschaftlern
- Forschungsdaten-Policies

#### Diskussion

- Es scheint regionale Beschränkungen zu geben. Sind Landesgrenzen bindend?
  Finanziell schon. 
- Kiel: dezentrales FDM
- HS bemerkt, dass es für ein kleines Institut schwierig ist, ein FDM zu 
  installieren, wenn dies in den Projekten nicht explizit eingeplant ist. 
  Antwort: Entscheidend dafür ist, was förderfähig ist. Empfehlung an das KWB: 
  Wir sollten uns Kooperationspartner (z.B. Uni mit Rechenzentrum?) suchen

### Session 3: Disziplinen-spezifische Besonderheiten im FDM

#### Projekt FDM_OAS-Orient, [Martin Lee](http://www.fu-berlin.de/sites/campusbib/Ansprechpartner/Lee-Martin/index.html), FU Berlin

- Fachbereichsbibliothek, Asiatische Sprachen
- Information Retrieval
- "Was Google nicht findet, existiert nicht" - NEIN

#### Projekt InPT-Dat, [Steffen Franke](http://www.inp-greifswald.de/web3.nsf/mitarbeiter?Openpage&Language=eng&Liste=Mitarbeitender&ID=10091), INP Greifswald

- INP = [Leibnitz-Institut für Plasmaforschung und Technologie e.V.](http://www.inp-greifswald.de),
  außeruniversitäre Forschungseinrichtung, 164 Mitarbeiter laut Homepage
- Konzept einer interdisziplinären Datenplattform
- physikalische, biologische, medizinische Daten

#### Projekt geo\_data\_node_gfz, [Roland Bertelmann](http://www.gfz-potsdam.de/wissenschaftliche-infrastruktur/bibliothek-und-informationsdienste/mitarbeiter/profil/roland-bertelmann), GFZ Potsdam

- Spannungsfeld spezifisch <-> generisch
- Domänen: privat, Gruppe, dauerhaft, Nachnutzung
- Metadaten: essentiell für Wiederverwendung (Reuse) und Findbarkeit
- Strukturelle Metadaten, z.B. DOI
- Datenpublikation mit DOI
- Standardisierte XML-Dateien
- Konsensbildung in Communities

#### Projekt GRAcE, [Jan Brase](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/jan-brase), Uni Göttingen

- eResearch-Infrastruktur am Campus Göttingen
- Etablierung von Disziplin-unabhängigen services
- Embedded Librarian: Datenmanager geht "rein ins Feld"

#### Projekt eeFDM, [Roman Gerlach](http://www.geographie.uni-jena.de/Lehrst%C3%BChle/Fernerkundung/Personal/Gerlach.html), Uni Jena

- Kontaktstelle FDM Uni Jena
- Biodiversitätsforschung
- Datenmanagement-Plattform
- Heterogenität
- Herausforderung: Datenpublikation
- Projektansatz: FDM-Plattform im Baukastenprinzip
- Koordination und Harmonisierung

#### Projekt FDMHerder, [Barbara Fichtl](https://www.herder-institut.de/en/institute-staff/staff/personen/person/fichtl.html), Herder-Institut Marburg (**Statement**)

#### Projekt FAKIN, [Hauke Sonnenberg](http://www.kompetenz-wasser.de/Team.14.0.html), KWB (**Statement**)

- Schon Goethe hat die Bedeutung des Wassers erkannt.
- Wir bearbeiten Fragen zum Thema Wasser in Bezug auf Quantität und Qualität
- Wir verarbeiten Daten in unterschiedlicher Quantität und Qualität
- Daten sind heterogen in Bezug auf Struktur, Formate, Metadatenbedarf
- Unsere Methoden: Datenbanken, Programmierung, Automatisierung
- Unsere Tools: zum Teil Eigenentwicklungen, maßgeschneiderte Lösungen
- Unsere Ziele: 
    + weiterhin Qualität unserer Ergebnisse
    + Standardisierung, Vereinheitlichung eigener Methoden
    + etablierte Lösungen statt Eigenentwicklungen
- Was können wir von Ihnen lernen?

#### Projekt FoDaKo, [Hans-Dieter Weckmann](https://www.zim.hhu.de/nc/das-zim/mitarbeiterinnen-und-mitarbeiter/detailansicht.html?tt_address%5Bperson%5D=2623&tt_address%5Bfunktion%5D=3011), Uni Düsseldorf (**Statement**)

- Rechenzentrumsleiter
- Aufbau von Kompetenzzentren
- Unterschiedliche Policies, je nach Disziplin
- nicht nur Metadaten sind Disziplinen-spezifisch

#### Diskussion

- elektronische Laborbücher, wer kennt gute?
- Plädoyer: Mit dem arbeiten, was da ist!
- [Dataverse](http://dataverse.org/) als Repositorium
- Sharepoint als Möglichkeit, Prozesse abzubilden
